
spring:

  #  server:
  #    port: 8081

  #  application:
  #    name:
  #
  #  profile:
  #    active:

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
    open-in-view: false
    show-sql: true

  # mybatis - jdbc
  mybatis:
    mapper-locations: classpath:mappers/**/**/*.xml
    type-aliases-package: practice.jpamybatis.entity

# logging
logging:
  level:
    root: info