
spring:

#  application:
#    name:
#
#  profile:
#    active:

  #thymeleaf 설정
  thymeleaf:
    check-template-location: true
    prefix: src/main/resources/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    suffix: .html   # 파일 확장자
    cache: false

  datasource:

    maria:
      driver-class-name: org.mariadb.jdbc.Driver
      url : "jdbc:mariadb://localhost:3306/practice?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
      username: root
      password:

    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
#      pool-name: pool-jiniworld_demo ?

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
    open-in-view: false
    show-sql: true
  server:
    port: 8080